version: '3'
services:
  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production


